input {
  # Tells Logstash to read the fake log file our Python script will generate
  file {
    path => "/var/log/siem_lab/security_events.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  # Our Python script will generate logs in JSON format, which is an industry standard
  # This filter tells Logstash to parse the JSON so Kibana can read individual fields (like IP addresses)
  json {
    source => "message"
  }
}

output {
  # Sends the parsed, readable logs into our Elasticsearch database
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "siem-lab-logs-%{+YYYY.MM.dd}"
  }
  
  # Also prints the logs to the terminal so we can troubleshoot if things break
  stdout {
    codec => rubydebug
  }
}
